name: CI for Flight Search System

on:
  push:
    branches:
      - main
      - develop
      - feature/**

  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - develop
      - feature/**
    paths:
      - '**'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello world
        run: echo "Hello world"

  build-the-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -D skipTests
